Update check_changelog.yml

diff --git a/.github/workflows/check_changelog.yml b/.github/workflows/check_changelog.yml
--- a/.github/workflows/check_changelog.yml
+++ b/.github/workflows/check_changelog.yml
@@ -8,22 +8,25 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ contains(github.event.pull_request.labels.*.name, 'no-changelog') == 0 }}
     steps:
-      - name: Get PR number and author
+      - name: Get PR number
         run: |
           echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
-          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
       - uses: actions/checkout@v2
         with:
-          fetch-depth: '0'      
-      - name: check the changelog
+          fetch-depth: '0'
+      - name: Check the changelog only if tests have been modified
         run: |
           set -xe
-          result=`grep "$PR_NUMBER" ./changelog.rst | grep "$PR_AUTHOR"`
-          if [ "$result" != "" ]
+          tests=`git diff --name-only master | grep tests`
+          if [ "$tests" != "" ]
           then
-            echo $result
-          else
-          then
-            echo "Changelog entry is missing."
-            exit 1
+            result=`grep "$PR_NUMBER" ./changelog.rst`
+            if [ "$result" != "" ]
+            then
+              echo $result
+            else
+            then
+              echo "Changelog entry is missing."
+              exit 1
+            fi
           fi
